import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js";
const USERNAME_KEY="lt3d_guest_name";
const el={canvas:document.getElementById("scene"),guestModal:document.getElementById("guestModal"),nameInput:document.getElementById("nameInput"),enterButton:document.getElementById("enterButton"),playerName:document.getElementById("playerName"),avatarInitials:document.getElementById("avatarInitials"),chatInput:document.getElementById("chatInput"),chatSend:document.getElementById("chatSend"),chatLog:document.getElementById("chatLog"),joystick:document.getElementById("joystick"),joystickKnob:document.getElementById("joystickKnob")};
const sanitizeName=v=>(v||"").replace(/[^a-z0-9 _-]/gi,"").trim().slice(0,16);
const initials=n=>{const c=sanitizeName(n)||"Guest";const p=c.split(/\s+/).filter(Boolean);return ((p[0]?.[0]||"G")+(p[1]?.[0]||c[1]||"" )).toUpperCase();};
function chat(text){const d=document.createElement("div");d.className="chat-message";d.textContent=text;el.chatLog.appendChild(d);el.chatLog.scrollTop=el.chatLog.scrollHeight;}
const renderer=new THREE.WebGLRenderer({canvas:el.canvas,antialias:true,alpha:false});renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(window.innerWidth,window.innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8bdfff);scene.fog=new THREE.FogExp2(0x8bdfff,.0045);const camera=new THREE.PerspectiveCamera(55,window.innerWidth/window.innerHeight,.1,1000);camera.position.set(0,12,22);const clock=new THREE.Clock();
scene.add(new THREE.HemisphereLight(0xeafcff,0xefbb78,1.5));const sun=new THREE.DirectionalLight(0xfff0cf,2.1);sun.position.set(40,50,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.near=.5;sun.shadow.camera.far=200;sun.shadow.camera.left=-90;sun.shadow.camera.right=90;sun.shadow.camera.top=90;sun.shadow.camera.bottom=-90;scene.add(sun);
const world=new THREE.Group();scene.add(world);const animated=[];const guests=[];
const sandMat=new THREE.MeshStandardMaterial({color:0xeac37f,roughness:.98});const pathMat=new THREE.MeshStandardMaterial({color:0xf4ddb0,roughness:.96});const woodMat=new THREE.MeshStandardMaterial({color:0x8a5c38,roughness:.95});const leafMat=new THREE.MeshStandardMaterial({color:0x2ec77d,roughness:.82});const rockMat=new THREE.MeshStandardMaterial({color:0x95a4b2,roughness:1});
function roundedRectPath(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
function spriteTexture(text,{w=512,h=140,fill='rgba(8,18,30,0.86)',color='#fff',fontSize=40}={}){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');roundedRectPath(ctx,12,12,w-24,h-24,28);ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.15)';ctx.lineWidth=4;ctx.stroke();ctx.fillStyle=color;ctx.font=`700 ${fontSize}px Inter, Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,w/2,h/2);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t;}
function label(text,w=7,h=1.8){const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:spriteTexture(text),transparent:true}));sp.scale.set(w,h,1);return sp;}
function shadow(x,z,s=1){const m=new THREE.Mesh(new THREE.CircleGeometry(2.5*s,24),new THREE.MeshStandardMaterial({color:0x0b1722,transparent:true,opacity:.14}));m.rotation.x=-Math.PI/2;m.position.set(x,.05,z);world.add(m);} 
function water(){const geo=new THREE.PlaneGeometry(520,520,110,110);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;const base=new Float32Array(pos.array);const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0x4ac7ff,roughness:.22,metalness:.02,transparent:true,opacity:.96}));mesh.position.y=-1.2;mesh.receiveShadow=true;world.add(mesh);const foam=new THREE.Mesh(new THREE.RingGeometry(106,122,96),new THREE.MeshStandardMaterial({color:0xf0ffff,transparent:true,opacity:.7}));foam.rotation.x=-Math.PI/2;foam.position.y=-1.08;world.add(foam);animated.push(t=>{const arr=pos.array;for(let i=0;i<arr.length;i+=3){const bx=base[i],by=base[i+1],bz=base[i+2];arr[i+1]=by+Math.sin((bx+t*16)*.035)*.48+Math.cos((bz-t*20)*.028)*.38;}pos.needsUpdate=true;geo.computeVertexNormals();foam.rotation.z=t*.02;});}
function island(){const isl=new THREE.Mesh(new THREE.CylinderGeometry(108,118,2.5,90),sandMat);isl.position.y=-.08;isl.receiveShadow=true;world.add(isl);for(const [g,p] of [[new THREE.CylinderGeometry(20,20,.18,48),[0,.08,18]],[new THREE.BoxGeometry(26,.18,14),[-28,.08,8]],[new THREE.BoxGeometry(18,.18,18),[34,.08,-8]],[new THREE.BoxGeometry(58,.12,6),[0,.07,2]],[new THREE.BoxGeometry(6,.12,42),[24,.07,-14]],[new THREE.BoxGeometry(8,.12,34),[-20,.07,9]]]){const m=new THREE.Mesh(g,pathMat);m.position.set(...p);world.add(m);}const boundary=new THREE.Mesh(new THREE.TorusGeometry(116,1.2,18,96),new THREE.MeshStandardMaterial({color:0xdaf4ff,transparent:true,opacity:.22}));boundary.rotation.x=-Math.PI/2;boundary.position.y=.06;world.add(boundary);for(const [t,x,y,z] of [['Beach Plaza',0,4.2,18],['Social Cove',-28,4.2,8],['NPC Corner',34,4.2,-8],['Mini Games Pier',36,4.2,-28]]){const l=label(t);l.position.set(x,y,z);world.add(l);}}
function palm(x,z,s=1){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.24*s,.38*s,6*s,10),new THREE.MeshStandardMaterial({color:0x9c6d41,roughness:1}));trunk.position.y=3*s;trunk.rotation.z=.14;trunk.castShadow=true;g.add(trunk);for(let i=0;i<5;i++){const leaf=new THREE.Mesh(new THREE.CapsuleGeometry(.16*s,4.2*s,4,12),leafMat);leaf.position.set(Math.cos(i/5*Math.PI*2)*.5,6*s,Math.sin(i/5*Math.PI*2)*.5);leaf.rotation.z=Math.PI/2;leaf.rotation.y=i/5*Math.PI*2;leaf.rotation.x=-.55;leaf.castShadow=true;g.add(leaf);}g.position.set(x,0,z);shadow(x,z,.85*s);world.add(g);} 
function bench(x,z,r=0){const g=new THREE.Group();const seat=new THREE.Mesh(new THREE.BoxGeometry(2.4,.18,.75),woodMat);seat.position.y=.85;const back=new THREE.Mesh(new THREE.BoxGeometry(2.4,1.1,.16),woodMat);back.position.set(0,1.35,-.32);g.add(seat,back);const legGeo=new THREE.BoxGeometry(.16,.85,.16);for(const [lx,lz] of [[-.95,.42],[.95,.42],[-.95,-.2],[.95,-.2]]){const leg=new THREE.Mesh(legGeo,new THREE.MeshStandardMaterial({color:0x53606b}));leg.position.set(lx,.42,lz);g.add(leg);}g.position.set(x,0,z);g.rotation.y=r;shadow(x,z,.5);world.add(g);} 
function rock(x,z,s=1){const r=new THREE.Mesh(new THREE.DodecahedronGeometry(1.2*s,0),rockMat);r.position.set(x,.9*s,z);r.rotation.set(Math.random()*.5,Math.random()*Math.PI,Math.random()*.3);shadow(x,z,.45*s);world.add(r);} 
function pier(x,z,len=24){const g=new THREE.Group();const deck=new THREE.Mesh(new THREE.BoxGeometry(4.8,.45,len),woodMat);deck.position.y=.32;g.add(deck);const postGeo=new THREE.BoxGeometry(.24,2.6,.24);for(let i=0;i<6;i++){const zl=-len/2+1.5+i*2.3;for(const sx of [-1.9,1.9]){const p=new THREE.Mesh(postGeo,new THREE.MeshStandardMaterial({color:0x6d4e33}));p.position.set(sx,-.8,zl);g.add(p);}}g.position.set(x,0,z);world.add(g);} 
function comingSoon(x,z){const g=new THREE.Group();const ring=new THREE.Mesh(new THREE.TorusGeometry(3.6,.22,18,42),new THREE.MeshStandardMaterial({color:0x54c2ff,emissive:0x1359b7,emissiveIntensity:.4}));ring.rotation.x=Math.PI/2;g.add(ring);const floor=new THREE.Mesh(new THREE.CircleGeometry(3.1,32),new THREE.MeshStandardMaterial({color:0x0c2030,transparent:true,opacity:.55}));floor.rotation.x=-Math.PI/2;floor.position.y=.01;g.add(floor);const l=label('COMING SOON',9,2.2);l.position.set(0,4.1,0);g.add(l);g.position.set(x,.04,z);world.add(g);animated.push(t=>{ring.rotation.z=t*.7;l.position.y=4.1+Math.sin(t*2+x)*.16;});}
function speechBubble(){const s=new THREE.Sprite(new THREE.SpriteMaterial({transparent:true}));s.visible=false;s.scale.set(6.6,2.2,1);return s;}
function setSpeech(s,text){s.material.map=spriteTexture(text,{w:640,h:160,fontSize:34});s.material.needsUpdate=true;s.visible=true;s.userData.expiresAt=performance.now()+4500;}
function avatar(color=0x62bfff){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.SphereGeometry(1.55,24,20),new THREE.MeshStandardMaterial({color,roughness:.62}));body.scale.set(1,1.08,1.28);body.position.y=2.85;g.add(body);const belly=new THREE.Mesh(new THREE.SphereGeometry(1.02,24,20),new THREE.MeshStandardMaterial({color:0xe9f8ff,roughness:.82}));belly.scale.set(.88,.95,1.04);belly.position.set(0,2.4,.92);g.add(belly);const head=new THREE.Mesh(new THREE.SphereGeometry(1.22,24,20),new THREE.MeshStandardMaterial({color:color+0x051010,roughness:.62}));head.position.set(0,3.9,.78);head.scale.set(1.02,.95,1.06);g.add(head);const snout=new THREE.Mesh(new THREE.CapsuleGeometry(.46,.55,4,10),new THREE.MeshStandardMaterial({color:0xe7f8ff,roughness:.8}));snout.rotation.x=Math.PI/2;snout.position.set(0,3.7,1.72);g.add(snout);const dorsal=new THREE.Mesh(new THREE.ConeGeometry(.52,1.35,12),new THREE.MeshStandardMaterial({color:0x4aa7e7,roughness:.68}));dorsal.position.set(0,4.72,.06);dorsal.rotation.z=Math.PI;g.add(dorsal);for(const sx of [-1.16,1.16]){const fin=new THREE.Mesh(new THREE.ConeGeometry(.42,1.08,10),new THREE.MeshStandardMaterial({color:0x52b2f0,roughness:.72}));fin.position.set(sx,2.9,.5);fin.rotation.z=sx<0?-Math.PI/2:Math.PI/2;fin.rotation.x=-.42;g.add(fin);}for(const sx of [-.34,.34]){const e=new THREE.Mesh(new THREE.SphereGeometry(.12,12,12),new THREE.MeshStandardMaterial({color:0x051018}));e.position.set(sx,4.08,1.66);g.add(e);}const shoeMat=new THREE.MeshStandardMaterial({color:0x2d7fff,roughness:.45});const soleMat=new THREE.MeshStandardMaterial({color:0xf3f9ff,roughness:.85});function shoe(x){const s=new THREE.Group();const base=new THREE.Mesh(new THREE.BoxGeometry(.96,.42,1.42),shoeMat);const sole=new THREE.Mesh(new THREE.BoxGeometry(1.02,.1,1.5),soleMat);sole.position.y=-.24;const tip=new THREE.Mesh(new THREE.SphereGeometry(.28,12,10),shoeMat);tip.scale.set(1.5,.8,1.3);tip.position.set(0,-.02,.62);s.add(base,sole,tip);s.position.set(x,.56,.42);return s;}const shoeL=shoe(-.62),shoeR=shoe(.62);g.add(shoeL,shoeR);const nameTag=label('Guest',6.2,1.55);nameTag.position.set(0,6.8,0);g.add(nameTag);const bubble=speechBubble();bubble.position.set(0,8.6,0);g.add(bubble);g.userData={shoeL,shoeR,nameTag,bubble};return g;}
function setNameTag(g,text){if(g.userData.nameTag)g.remove(g.userData.nameTag);const n=label(text,6.2,1.55);n.position.set(0,6.8,0);g.userData.nameTag=n;g.add(n);} 
function makePlayer(){const g=avatar(0x62bfff);g.position.set(0,0,22);shadow(0,22,.72);world.add(g);return g;} 
function makeGuest(name,x,z,color){const g=avatar(color);g.position.set(x,0,z);setNameTag(g,name);g.userData.home=new THREE.Vector3(x,0,z);g.userData.phase=Math.random()*Math.PI*2;shadow(x,z,.6);world.add(g);guests.push(g);} 
water();island();for(const [x,z,s] of [[-42,36,1.15],[-56,6,1.1],[-64,-28,1.2],[-28,-50,1.1],[12,-60,1.18],[54,-46,1.2],[68,-4,1.05],[56,34,1.15],[20,58,1.2],[-10,64,1.1],[88,18,1.25],[-86,-8,1.12]]) palm(x,z,s);for(const [x,z,r] of [[-40,0,0],[-34,0,Math.PI/2],[-24,2,Math.PI]]) bench(x,z,r);for(const [x,z,s] of [[12,-18,1.2],[18,-24,1],[6,-26,.9],[62,8,1.2],[-58,-18,1.05],[48,40,1.1]]) rock(x,z,s);pier(38,-28,26);comingSoon(-72,58);comingSoon(84,58);comingSoon(92,-62);
const player=makePlayer();makeGuest('Luna',-20,12,0xff8cbc);makeGuest('Kai',34,-12,0xa0d8ff);makeGuest('Nova',8,28,0xffd27a);
let cameraYaw=0,cameraPitch=.28,drag=false,lastX=0,lastY=0;const keys=new Set();window.addEventListener('keydown',e=>keys.add(e.key.toLowerCase()));window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('pointerdown',e=>{if(!el.guestModal.classList.contains('hidden'))return;const t=e.target;if(t instanceof Element&&(t.closest('.joystick')||t.closest('.guest-card')||t.closest('.chat-panel'))) return;drag=true;lastX=e.clientX;lastY=e.clientY;});window.addEventListener('pointerup',()=>drag=false);window.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;cameraYaw-=dx*.0032;cameraPitch=THREE.MathUtils.clamp(cameraPitch-dy*.0022,.14,.72);lastX=e.clientX;lastY=e.clientY;});
const joy={active:false,x:0,y:0,pointerId:null};function resetJoy(){joy.active=false;joy.x=0;joy.y=0;joy.pointerId=null;el.joystickKnob.style.transform='translate(-50%, -50%)';}el.joystick.addEventListener('pointerdown',e=>{joy.active=true;joy.pointerId=e.pointerId;el.joystick.setPointerCapture(e.pointerId);});el.joystick.addEventListener('pointermove',e=>{if(!joy.active||e.pointerId!==joy.pointerId)return;const r=el.joystick.getBoundingClientRect();const cx=r.left+r.width/2,cy=r.top+r.height/2;let dx=e.clientX-cx,dy=e.clientY-cy;const max=r.width*.28;const len=Math.hypot(dx,dy)||1;if(len>max){dx=dx/len*max;dy=dy/len*max;}joy.x=dx/max;joy.y=dy/max;el.joystickKnob.style.transform=`translate(calc(-50% + ${dx}px), calc(-50% + ${dy}px))`;});el.joystick.addEventListener('pointerup',resetJoy);el.joystick.addEventListener('pointercancel',resetJoy);
function setGuestName(name){const clean=sanitizeName(name)||'Guest';localStorage.setItem(USERNAME_KEY,clean);el.playerName.textContent=clean;el.avatarInitials.textContent=initials(clean);setNameTag(player,clean);}function enterHub(name){const clean=sanitizeName(name)||'Guest';setGuestName(clean);el.guestModal.classList.add('hidden');el.guestModal.setAttribute('aria-hidden','true');chat(`${clean} joined the hub.`);setTimeout(()=>el.chatInput.focus(),50);}function submitGuest(ev){if(ev){ev.preventDefault();ev.stopPropagation();}const clean=sanitizeName(el.nameInput.value);if(!clean){el.nameInput.value='';el.nameInput.focus();return;}enterHub(clean);}el.enterButton.addEventListener('click',submitGuest);el.nameInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();e.stopPropagation();submitGuest(e);}});const stored=localStorage.getItem(USERNAME_KEY);if(stored)enterHub(stored);else{el.guestModal.classList.remove('hidden');el.nameInput.focus();}
function sendChat(){const v=(el.chatInput.value||'').trim();if(!v)return;const n=el.playerName.textContent||'Guest';chat(`${n}: ${v}`);setSpeech(player.userData.bubble,v.slice(0,34));el.chatInput.value='';}el.chatSend.addEventListener('click',sendChat);el.chatInput.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendChat();}});
const blocked=[{x:-72,z:58,r:6.2},{x:84,z:58,r:6.2},{x:92,z:-62,r:6.2}],worldRadius=108,playerRadius=2.2;
function movementInput(){let x=0,z=0;if(keys.has('w')||keys.has('arrowup'))z-=1;if(keys.has('s')||keys.has('arrowdown'))z+=1;if(keys.has('a')||keys.has('arrowleft'))x-=1;if(keys.has('d')||keys.has('arrowright'))x+=1;x+=joy.x;z+=joy.y;const v=new THREE.Vector3(x,0,z);if(v.lengthSq()>1)v.normalize();return v;}
function applyBounds(p){const len=Math.hypot(p.x,p.z);if(len>worldRadius-playerRadius){p.x=p.x/len*(worldRadius-playerRadius);p.z=p.z/len*(worldRadius-playerRadius);}for(const zone of blocked){const dx=p.x-zone.x,dz=p.z-zone.z,dist=Math.hypot(dx,dz);if(dist<zone.r+playerRadius){const safe=zone.r+playerRadius,nx=dx/(dist||1),nz=dz/(dist||1);p.x=zone.x+nx*safe;p.z=zone.z+nz*safe;}}}
function animatePlayer(delta,time){const input=movementInput();const sprint=keys.has('shift')?1.5:1,speed=10.5*sprint;if(input.lengthSq()>0){const f=new THREE.Vector3(Math.sin(cameraYaw),0,Math.cos(cameraYaw));const r=new THREE.Vector3(f.z,0,-f.x);const move=f.multiplyScalar(-input.z).add(r.multiplyScalar(input.x)).normalize().multiplyScalar(speed*delta);player.position.add(move);applyBounds(player.position);const faceYaw=Math.atan2(move.x,move.z);player.rotation.y=THREE.MathUtils.lerp(player.rotation.y,faceYaw,.18);const swing=Math.sin(time*12*sprint)*.18;player.userData.shoeL.rotation.x=swing;player.userData.shoeR.rotation.x=-swing;player.position.y=Math.sin(time*24*sprint)*.04;}else{player.userData.shoeL.rotation.x=THREE.MathUtils.lerp(player.userData.shoeL.rotation.x,0,.18);player.userData.shoeR.rotation.x=THREE.MathUtils.lerp(player.userData.shoeR.rotation.x,0,.18);player.position.y=Math.sin(time*2)*.02;}if(player.userData.bubble.visible&&performance.now()>(player.userData.bubble.userData.expiresAt||0))player.userData.bubble.visible=false;const target=player.position.clone().add(new THREE.Vector3(0,4.1,0));const desired=new THREE.Vector3(player.position.x+Math.sin(cameraYaw)*Math.cos(cameraPitch)*20,player.position.y+11.2+Math.sin(cameraPitch)*6.8,player.position.z+Math.cos(cameraYaw)*Math.cos(cameraPitch)*20);camera.position.lerp(desired,.08);camera.lookAt(target);} 
function animateGuests(time){guests.forEach((g,i)=>{const p=time*.55+g.userData.phase;g.position.x=g.userData.home.x+Math.sin(p)*1.8;g.position.z=g.userData.home.z+Math.cos(p*.8)*1.6;g.rotation.y=Math.sin(p*1.4)*.5;const swing=Math.sin(time*6+i)*.1;g.userData.shoeL.rotation.x=swing;g.userData.shoeR.rotation.x=-swing;});}
function loop(){const delta=Math.min(clock.getDelta(),.033),time=clock.elapsedTime;animated.forEach(fn=>fn(time,delta));animatePlayer(delta,time);animateGuests(time);renderer.render(scene,camera);requestAnimationFrame(loop);}loop();window.addEventListener('resize',()=>{camera.aspect=window.innerWidth/window.innerHeight;camera.updateProjectionMatrix();renderer.setSize(window.innerWidth,window.innerHeight);});
